version: '3.8'

services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABRICKS_HOST=${DATABRICKS_HOST}
      - DATABRICKS_HTTP_PATH=${DATABRICKS_HTTP_PATH}
      - DATABRICKS_TOKEN=${DATABRICKS_TOKEN}
      - DATABRICKS_CATALOG=${DATABRICKS_CATALOG}
      - DATABRICKS_SCHEMA=${DATABRICKS_SCHEMA}
    volumes:
      - .:/app